"""
Database models for the XAU Auto Trader project.

These SQLAlchemy models define the core tables used to store:
- generated trading signals
- executed/simulated trades
- daily performance statistics
- equity curve values
- application/runtime errors

Live trading is intentionally not implemented here.
"""

from datetime import datetime, date
from sqlalchemy import Boolean, Date, DateTime, Float, Integer, String, Text
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """Base class for all SQLAlchemy models."""


class Signal(Base):
    """Trading signal generated by the strategy before risk approval."""

    __tablename__ = "signals"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    timestamp: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, nullable=False)

    symbol: Mapped[str] = mapped_column(String(20), nullable=False, default="XAUUSD")
    timeframe: Mapped[str] = mapped_column(String(10), nullable=False)
    side: Mapped[str] = mapped_column(String(10), nullable=False)  # BUY, SELL, NO_TRADE

    entry_price: Mapped[float | None] = mapped_column(Float, nullable=True)
    stop_loss: Mapped[float | None] = mapped_column(Float, nullable=True)
    take_profit: Mapped[float | None] = mapped_column(Float, nullable=True)

    confidence: Mapped[float | None] = mapped_column(Float, nullable=True)
    risk_reward: Mapped[float | None] = mapped_column(Float, nullable=True)

    reason: Mapped[str | None] = mapped_column(Text, nullable=True)
    approved_by_risk_manager: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    blocked_reason: Mapped[str | None] = mapped_column(Text, nullable=True)


class Trade(Base):
    """Executed or simulated trade saved by backtest, paper trading, or future live mode."""

    __tablename__ = "trades"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    timestamp_open: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    timestamp_close: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)

    symbol: Mapped[str] = mapped_column(String(20), nullable=False, default="XAUUSD")
    side: Mapped[str] = mapped_column(String(10), nullable=False)  # BUY or SELL
    timeframe: Mapped[str] = mapped_column(String(10), nullable=False)

    entry_price: Mapped[float] = mapped_column(Float, nullable=False)
    stop_loss: Mapped[float] = mapped_column(Float, nullable=False)
    take_profit: Mapped[float] = mapped_column(Float, nullable=False)
    exit_price: Mapped[float | None] = mapped_column(Float, nullable=True)

    position_size: Mapped[float] = mapped_column(Float, nullable=False)
    risk_percent: Mapped[float] = mapped_column(Float, nullable=False)
    risk_amount: Mapped[float] = mapped_column(Float, nullable=False)

    result: Mapped[str | None] = mapped_column(String(20), nullable=True)  # WIN, LOSS, BREAKEVEN, OPEN
    profit_loss: Mapped[float | None] = mapped_column(Float, nullable=True)
    risk_reward: Mapped[float | None] = mapped_column(Float, nullable=True)

    strategy_name: Mapped[str] = mapped_column(String(100), nullable=False, default="default")
    mode: Mapped[str] = mapped_column(String(20), nullable=False, default="backtest")  # backtest/paper/live

    reason_entry: Mapped[str | None] = mapped_column(Text, nullable=True)
    reason_exit: Mapped[str | None] = mapped_column(Text, nullable=True)


class DailyStats(Base):
    """Daily performance and risk statistics."""

    __tablename__ = "daily_stats"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    trading_date: Mapped[date] = mapped_column(Date, nullable=False, unique=True)

    starting_balance: Mapped[float] = mapped_column(Float, nullable=False)
    ending_balance: Mapped[float] = mapped_column(Float, nullable=False)
    daily_pnl: Mapped[float] = mapped_column(Float, nullable=False)
    daily_drawdown: Mapped[float] = mapped_column(Float, nullable=False)

    trades_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    wins: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    losses: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    max_consecutive_losses: Mapped[int] = mapped_column(Integer, default=0, nullable=False)

    trading_allowed: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)


class EquityCurve(Base):
    """Equity curve snapshot saved during backtest or paper trading."""

    __tablename__ = "equity_curve"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    timestamp: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, nullable=False)

    balance: Mapped[float] = mapped_column(Float, nullable=False)
    equity: Mapped[float] = mapped_column(Float, nullable=False)
    drawdown: Mapped[float] = mapped_column(Float, nullable=False)
    mode: Mapped[str] = mapped_column(String(20), nullable=False, default="backtest")


class ErrorLog(Base):
    """Application error log stored in the database."""

    __tablename__ = "errors"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    timestamp: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, nullable=False)

    module: Mapped[str] = mapped_column(String(100), nullable=False)
    error_type: Mapped[str] = mapped_column(String(100), nullable=False)
    message: Mapped[str] = mapped_column(Text, nullable=False)
    details: Mapped[str | None] = mapped_column(Text, nullable=True)
